FROM python:3.12-slim

WORKDIR /app

# Instalar dependencias
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copiar proyecto
COPY . .

# Puerto FastAPI
EXPOSE 8000

# Ejecutar uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]